[workspace]
authors = ["mt-sette <mt-sette@proton.me>"]
channels = ["conda-forge"]
name = "liane_lib"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
start = "streamlit run  ./src/main.py"

[dependencies]
streamlit = ">=1.51.0,<2"
sqlalchemy = ">=2.0.44,<3"
pandas = ">=2.3.3,<3"
pymysql = ">=1.1.2,<2"
python-dotenv = ">=1.2.1,<2"
